# Generated by Django 5.2.6 on 2025-09-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_affiliate_stripe_account_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='roth_conversion_calculated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last Roth conversion calculation', null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='roth_conversion_results',
            field=models.JSONField(blank=True, help_text='Stored Roth conversion calculation results for debugging and prepopulation', null=True),
        ),
    ]
