# Generated by Django 5.2.7 on 2025-10-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_roth_conversion_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='survivor_takes_higher_benefit',
            field=models.BooleanField(default=False, help_text='Surviving spouse takes higher SS benefit'),
        ),
    ]
