# Generated by Django 5.2.7 on 2025-10-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_survivor_takes_higher_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when scenario was archived', null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived scenarios are hidden but retained for RIA compliance'),
        ),
    ]
